<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Punkty edukacyjne mikkie_course-thumb</name>
   <tag></tag>
   <elementGuidId>673639db-5cd6-45ed-b5f9-ab83c6f51be9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yui_3_17_2_1_1612534326494_25']/div[2]/div/div/div/div[4]/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.aptekarska.pl/oferta/pluginfile.php/14824/course/overviewfiles/Obraz1.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Course Image Nietrzymanie moczu jako czynnik wpływający na jakość snu u pacjentów w wieku podeszłym</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>course-thumb</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1612534326494_25&quot;)/div[@class=&quot;course_category_tree clearfix&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;courses category-browse category-browse-6&quot;]/div[@class=&quot;courses-wrapper&quot;]/div[@class=&quot;theme-course-item&quot;]/div[@class=&quot;course-item-inner inner collapsed&quot;]/a[1]/div[@class=&quot;course-thumb-holder hasimage&quot;]/img[@class=&quot;course-thumb&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1612534326494_25']/div[2]/div/div/div/div[4]/div/a/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Course Image Nietrzymanie moczu jako czynnik wpływający na jakość snu u pacjentów w wieku podeszłym']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a/div/img</value>
   </webElementXpaths>
</WebElementEntity>
